package com.fastchat.FastChat.client.gui;

import com.fastchat.FastChat.client.OnlineUsersInterface;
import com.fastchat.FastChat.util.Localization;

import javax.swing.*;
import java.awt.*;

public class OnlineUsersGUI extends OnlineUsersInterface {
	private JFrame frame;
	private JPanel panel;
	private JList<String> userList;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	OnlineUsersGUI() {
		init();
	}

	@Override
	protected void init() {
		frame = new JFrame();
		frame.setType(JFrame.Type.UTILITY);
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.setSize(278, 409);
		frame.setLocationRelativeTo(null);
		frame.setTitle(Localization.get("menu_bar_online_users"));
		frame.setContentPane(panel);
	}

	@Override
	protected void update(String[] users) {
		userList.setListData(users);
	}

	@Override
	protected void show() {
		frame.setVisible(true);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new GridBagLayout());
		final JScrollPane scrollPane1 = new JScrollPane();
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.ipadx = 5;
		gbc.ipady = 5;
		panel.add(scrollPane1, gbc);
		userList = new JList();
		scrollPane1.setViewportView(userList);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
